### ISSUE TITLE
Failing on current github actions

### ISSUE THREAD

**Issue by mballoni** [rahulsom/gradle-up#2]
I'm trying to use this action but it fails with the following message:
```
(23) Failed writing body
##[error]Docker run failed with exit code 1
```

Here is the execution:
https://github.com/mballoni/boot-validator/commit/76a6a17e150398d8aebc57a7cf679acf93d11add/checks?check_suite_id=357269677

And the github action workflow:
https://github.com/mballoni/boot-validator/blob/master/.github/workflows/gradlew-update.yml

Am I missing something?
Thank you!

**Comment by MairwunNx** [comment]
Probably need define `JAVA_HOME` variable. I think path value is wrong.

`/opt/hostedtoolcache/jdk/11.0.5/x64/bin/java` need replace on `/opt/hostedtoolcache/jdk/11.0.5/x64/bin`

**Comment by koppor** [comment]
I played long around at https://github.com/JabRef/jabref/pull/6030

```
  env:
    JAVA_HOME: /opt/hostedtoolcache/jdk/11.0.6/x64
    JAVA_HOME_11.0.6_x64: /opt/hostedtoolcache/jdk/11.0.6/x64
-rwxr-xr-x 1 root root 9753 Dec 27 05:35 /usr/lib/jvm/zulu-11-azure-amd64/bin/java
```

`java -version` leads to `openjdk version "11.0.6" 2020-01-14 LTS`

Still there is

    groovy: JAVA_HOME is not defined correctly, can not execute: /usr/lib/jvm/zulu-11-azure-amd64/bin/java
